### ISSUE TITLE
Enable blog

### ISSUE THREAD

**Issue by yungyuc** [yungyuc/sciwork20#14]
Pelican supports blog and let's come up with a way to use it for online promotion.

**Comment by yungyuc** [comment]
Something's wrong (see below).  Fixing.

<img width="1209" alt="Screen Shot 2019-12-16 at 19 16 04" src="https://user-images.githubusercontent.com/399122/70902816-8af83080-2038-11ea-857b-8dfe1f1afa60.png">

**Comment by yungyuc** [comment]
Fixed with PR #20 

<img width="1028" alt="Screen Shot 2019-12-16 at 19 24 45" src="https://user-images.githubusercontent.com/399122/70903372-baf40380-2039-11ea-8b50-e19cb9926e37.png">

**Comment by chestercheng** [comment]
The pages URL also having the same issue.

 I've been checked all of the `href` attribute in HTML make sure it will be correct,
and fixed with commit [402ae6c](https://github.com/yungyuc/sciwork20/commit/402ae6cb91b7bd33d561a486c5c4ecf461a9ba82)

**Comment by yungyuc** [comment]
Thanks a lot!

**Comment by yungyuc** [comment]
Blog system is published.
