### ISSUE TITLE
Disable directory listing in Apache

### ISSUE THREAD

**Issue by chestercheng** [yungyuc/sciwork20#28]
As title, default indexing is enabled in Apache.

We can set the `Options -Indexes` in Virtual Host or `.htaccess` file to disable it.

<img width="665" alt="Screen Shot 2019-12-19 at 11 57 21 AM" src="https://user-images.githubusercontent.com/36478905/71143811-ce2fea80-2256-11ea-92fd-ff2bbefe40ac.png">

**Comment by yungyuc** [comment]
Wow.  Thanks a lot for spotting this.  Will fix soon.

**Comment by yungyuc** [comment]
Fixed.

![Screen Shot 2019-12-19 at 14 22 46](https://user-images.githubusercontent.com/399122/71149982-15c07180-226b-11ea-8a72-044252d1ff8c.png)
